### ISSUE TITLE
Delete client shows error on screen

### ISSUE THREAD

**Issue by altomarketing** [sentora/sentora-core#253]
For bug reports please provide the following information:

Operating System: centos 

Operating System Version number: 6

Sentora Version: 

**Issue: delete client show error on screen**

How to reproduce it:

```
Critical Error: [0144] - Sentora database 'exec' error (42000).

A database query has caused an error, the details of which can be found below.

Error message:

 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'sentora_core.alias' doesn't exist) :(', '')' at line 1

SQL Executed:

INSERT INTO x_logs (lg_user_fk, lg_code_vc, lg_module_vc, lg_detail_tx, lg_stack_tx) VALUES (0, '861', 'NA', 'Execute hook file (modules/forwarders/hooks/OnAfterDeleteClient.hook.php) -> Exception(SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sentora_core.alias' doesn't exist) :(', '')

Stack trace: 

Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'sentora_core.alias' doesn't exist) :(', '')' at line 1' in /etc/sentora/panel/dryden/db/driver.class.php:147

#0 /etc/sentora/panel/dryden/db/driver.class.php(147): PDO->exec('INSERT INTO x_l...')
#1 /etc/sentora/panel/dryden/debug/logger.class.php(66): db_driver->exec('INSERT INTO x_l...')
#2 /etc/sentora/panel/dryden/runtime/hook.class.php(36): debug_logger->writeLog()
#3 /etc/sentora/panel/modules/manage_clients/code/controller.ext.php(382): runtime_hook::Execute('OnAfterDeleteCl...')
#4 /etc/sentora/panel/modules/manage_clients/code/controller.ext.php(791): module_controller::ExecuteDeleteClient('10', '1')
#5 [internal function]: module_controller::doDeleteClient()
#6 /etc/sentora/panel/dryden/runtime/controller.class.php(65): call_user_func(Array)
#7 /etc/sentora/panel/inc/init.inc.php(145): runtime_controller->Init()
#8 /etc/sentora/panel/index.php(21): require_once('/etc/sentora/pa...')
#9 {main}


Thank you on the behalf of the Sentora Team.

V 0.0.2

```

**Comment by MBlagui** [comment]
@altomarketing 
Error say MARIADB while you state centos 6. That means you some how changed sentora stack. I'm sure in the process you created this bug.

For not a bug unless you explain how you got mariaDB setup there.

**Comment by altomarketing** [comment]
I just installed fresh Sentora on a fresh vps with latest centos 6, i did not install mariadb manually

**Comment by MBlagui** [comment]
Centos 6 ships with MySQL not with mariaDB. So this is not the default centos 6 minimal and thus the error.

**Comment by altomarketing** [comment]
sorry, you are right I used **Centos 7 **. Sorry about that

**Comment by bluebrad** [comment]
i  found this 
---
It's quite simple JoJo:
1. Open the file found in "etc/zpanel/panel/etc/zppy/repo.list
2. Delete all the info in the file
3. Run in your terminal "zppy update"
4. Open Repo Browser again and you should be good to go

but the site link is dead!

what is the new link will there be patch?
